export const DATA_REQUEST_STARTED = "LOGIN_REQUEST_STARTED";
export const DATA_REQUEST_SUCCESS = "DATA_REQUEST_SUCCESS";
export const DATA_REQUEST_FAILURE = "DATA_REQUEST_FAILURE";

export const ADD_FAVORITE_STARTED = "ADD_FAVORITE_STARTED";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILURE = "ADD_FAVORITE_FAILURE";

export const REMOVE_FAVORITE_STARTED = "REMOVE_FAVORITE_STARTED";
export const REMOVE_FAVORITE_SUCCESS = "REMOVE_FAVORITE_SUCCESS";
export const REMOVE_FAVORITE_FAILURE = "REMOVE_FAVORITE_FAILURE";

export const ADD_CART_STARTED = "ADD_CART_STARTED";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";

export const REMOVE_CART_STARTED = "REMOVE_CART_STARTED";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAILURE = "REMOVE_CART_FAILURE";

export const ADD_CONFIRM_MODAL = "ADD_CONFIRM_MODAL";
export const REMOVE_CONFIRM_MODAL = "REMOVE_CONFIRM_MODAL";

export const ADD_REGECT_MODAL = "ADD_REGECT_MODAL";
export const REMOVE_REGECT_MODAL = "REMOVE_REGECT_MODAL";


